[package]
edition = "2021"
name = "clam-sigutil"
version = "0.1.0"

[features]
default = []
validate_regex = ["regex"]

[dependencies]
anyhow = "1"
downcast-rs = "1"
enum-variants-strings = "0.1"
hex = "0.4"
hex-literal = "0.3"
itertools = "0.10"
num-derive = "0.3"
num-traits = "0.2"
structopt = "0.3"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1"
url = "2"

# Optional crates
regex = {version = "1", optional = true}

[[bin]]
name = "clam-sigutil"
path = "src/cmdline.rs"

[build-dependencies]
change-case = "0.2"
