[package]
edition = "2021"
name = "clam-sigutil"
version = "0.1.0"

[features]
default = []
validate_regex = ["regex"]

[dependencies]
anyhow = "1"
hex = "0.4"
itertools = "0.10"
num-derive = "0.3"
num-traits = "0.2"
structopt = "0.3"
strum = "0.23"
strum_macros = "0.23"
thiserror = "1"

# Optional crates
regex = {version = "1.5.4", optional = true}
enum-variants-strings = "0.1.0"

[[bin]]
name = "clam-sigutil"
path = "src/cmdline.rs"
